### ISSUE TITLE
Problem with UnboundLocalError showing in log file

### ISSUE THREAD

**Issue by sumocomputers** [Ramias1/indigo-pi-hole#1]
Every so often, I am getting errors in the logs as shown below (I turned on advanced logging). I am on 1.1.0 and Indigo 7.4.1.

I tried stopping and starting the plugin, reloading the plugin, and even shutting down and starting up the Indigo Server itself.

None worked. Rebooting the Mac is the only thing that works, for a time.

I should note that I have 2 PiHoles, and both are called out as separate devices in Indigo.

```
Traceback (most recent call last):
  File "plugin.py", line 163, in runConcurrentThread
  File "plugin.py", line 140, in udpateStatus
UnboundLocalError: local variable 'response' referenced before assignment

   Pi Hole DNS Controller Error    plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
   Pi Hole DNS Controller Debug    Starting concurrent thread
   Pi Hole DNS Controller Debug    Sent "PiHole Primary" status request
   Pi Hole DNS Controller Debug    PiHole is Enabled
   Pi Hole DNS Controller Debug    Sent "PiHole Secondary" status request
   Pi Hole DNS Controller Error    Error in plugin execution runConcurrentThread:
```

**Comment by Ramias1** [comment]
Should be fixed in version 2.1.1.  Please let me know if it is not.
