### ISSUE TITLE
Plugin Broken with Pi-hole v5.14.2

### ISSUE THREAD

**Issue by sumocomputers** [Ramias1/indigo-pi-hole#5]
With the following Pi-hole versions, Indigo plugin seems broken (log errors below).

Pi-hole [v5.14.2](https://github.com/pi-hole/pi-hole/releases/v5.14.2)
FTL [v5.20](https://github.com/pi-hole/FTL/releases/v5.20)
Web Interface [v5.18](https://github.com/pi-hole/AdminLTE/releases/v5.18)

```
Pi Hole DNS Controller Error    plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
Pi Hole DNS Controller Error    Error in plugin execution runConcurrentThread:

File "plugin.py", line 164, in runConcurrentThread
File "plugin.py", line 141, in udpateStatus
type: local variable 'response' referenced before assignment
```

**Comment by EagleDTW** [comment]
@sumocomputers This solved it for me changing line 131 in plugin.py to:
url = u"http://" + dev.pluginProps["address"] + "/admin/api.php?status&auth=" + dev.pluginProps["password"]

Please see issue #2

**Comment by Ramias1** [comment]
see version 2.1.1
